//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.reserves = new HashSet<reserve>();
        }
    
        public string ID { get; set; }
        public string Sh_bimar { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string mobile { get; set; }
        public string age { get; set; }
    
        public virtual Patient Patient1 { get; set; }
        public virtual Patient Patient2 { get; set; }
        public virtual ICollection<reserve> reserves { get; set; }
    }
}
