//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserve
    {
        public string ID { get; set; }
        public string Sh_bimar { get; set; }
        public string date_reserve { get; set; }
        public string az_hour { get; set; }
        public string ta_hour { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
